version: '3'
services:
  guacamoledb:
    container_name: guacamoledb
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "4a3TlySfT0LNnItSCA"
      MYSQL_DATABASE: "guacamole_db"
      MYSQL_USER: "guacamole_user"
      MYSQL_PASSWORD: "4a3TlySfT0LNnItSCA"
    volumes:
      - '/home/administrator/db-data:/var/lib/mysql'
  guacd:
    container_name: guacd
    image: guacamole/guacd:1.5.4
    restart: unless-stopped
  guacamole:
    container_name: guacamole
    image: guacamole/guacamole:1.5.4
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      GUACD_HOSTNAME: "guacd"
      MYSQL_HOSTNAME: "guacamoledb"
      MYSQL_DATABASE: "guacamole_db"
      MYSQL_USER: "guacamole_user"
      MYSQL_PASSWORD: "4a3TlySfT0LNnItSCA"
      TOTP_ENABLED: "false"
      GUACAMOLE_HOME: /etc/guacamole
    
    volumes:
      - '/home/administrator/guacamole/etc:/etc/guacamole'
      - '/home/administrator/guacamole/tomcat:/home/guacamole/tomcat'
      
          
     
    depends_on:
     - guacamoledb
     - guacd
volumes:
  db-data:

