version: '3'
services:
  guacamoledb:
    container_name: guacamoledb
    image: mariadb:11.2.2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '4a3TlySfT0LNnItSCA'
      MYSQL_DATABASE: 'guacamole_db'
      MYSQL_USER: 'guacamole_user'
      MYSQL_PASSWORD: '4a3TlySfT0LNnItm'
    volumes:
      - '/home/administrator/db-data:/var/lib/mysql'
  guacd:
    container_name: guacd
    image: guacamole/guacd:1.5.4
    restart: unless-stopped
  guacamole:
    container_name: guacamole
    image: guacamole/guacamole:1.5.4
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      GUACD_HOSTNAME: "guacd"
      MYSQL_HOSTNAME: "guacamoledb"
      MYSQL_DATABASE: "guacamole_db"
      MYSQL_USER: "guacamole_user"
      MYSQL_PASSWORD: "4a3TlySfT0LNnItmSCA"
      TOTP_ENABLED: "false"
      GUACAMOLE_HOME: /etc/guacamole
    volumes:
      - '/home/administrator/guacamole:/etc/guacamole'
    depends_on:
     - guacamoledb
     - guacd
volumes:
  db-data:
